### ISSUE TITLE
Problem with some characters in title

### ISSUE THREAD

**Issue by Lockszmith-GH** [izanaginookami10/web_to_epub#2]
I got this error:
```
Traceback (most recent call last):
  File "D:\_\bin\Web-to-epub\epub_converter.py", line 199, in <module>
    chapter_title = f.clean('raw-' + file_name + '.html', 'clean-'
  File "D:\_\bin\Web-to-epub\functions.py", line 320, in clean
    chapter, chapter_title = get_chapter_content(file_name_in, info,
  File "D:\_\bin\Web-to-epub\functions.py", line 228, in get_chapter_content
    with open(debug_folder + '\\' + chapter_title + '.html', 'w',
FileNotFoundError: [Errno 2] No such file or directory: '_debug About — Godot Engine (stable) documentation in English\\I/O — Godot Engine (stable) documentation in English.html'
```

I believe the issue to be related to the '/' in the title.

You're probably saving each page with the title, and the '/' isn't a valid filename character.

The link it's failing on is:
```
https://docs.godotengine.org/en/stable/tutorials/io/index.html
```

**Comment by Lockszmith-GH** [comment]
I already know that the following characters in titles create issues:
`\`,`/`,`:`,`*`,`?`
